name: cancer_prediction
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=2.2.2
  - numpy=1.26.4
  - matplotlib=3.9.2
  - seaborn=0.13.2
  - scikit-learn=1.7.2
  - imbalanced-learn=0.14.0
  - jupyter=1.0.0
  - notebook=7.2.2